# Endpoint URL
# query_url: https://endpoint.mint.isi.edu/modelCatalog-1.4.0/query
query_url: https://endpoint.mint.isi.edu/modelCatalog-1.4.0/query
# URL of the graph within the endpoint
graph:
#  - http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/mint@isi.edu
  - http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/mint@isi.edu
  - http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/texas@isi.edu
  - http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/coertel@mitre.org
  - http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/brandon@starsift.com
  - http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/hvarg@isi.edu
# Namespace prefix of the ontologies to load
ontology:
  - url: "https://w3id.org/okn/o/sd#"
    exclude:
      - SoftwareImage
  - url: "https://w3id.org/okn/o/sdm#"
    exclude:
      - Theory-GuidedModel
      - EmpiricalModel
      - PointBasedGrid
      - SpatiallyDistributedGrid
      - StandardVariable
      - Subsidy
      - FarmingPractices
      - Unit
      - Variable
      - Software
      - SoftwareConfiguration
      - ConfigurationSetup
#Use labels instead of URIs for the following properties:
useLabel:
  - https://w3id.org/okn/o/sd#usesUnit
  - https://w3id.org/okn/o/sd#hasSoftwareImage
  - https://w3id.org/okn/o/sd#hasStandardVariable
  - https://w3id.org/okn/o/sdm#intervalUnit
  - https://w3id.org/okn/o/sdm#usefulForCalculatingIndex
# Namespace prefix of the instances (to create shortcuts)
instance_uri_prefix: https://w3id.org/okn/i/mint/
# Export path folder
outPath: "catalog_export"
